server {
    listen 80;
    server_name zeyushujiaxuexi.top www.zeyushujiaxuexi.top;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name zeyushujiaxuexi.top www.zeyushujiaxuexi.top;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    add_header Server "MyLab/1.0";

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
